[module]
    [module.hugoVersion]
        extended = true
        min = "0.75.0"

    [[module.mounts]]
        source = "layouts"
        target = "layouts"

    [[module.mounts]]
        source = "assets"
        target = "assets"